<%@ page language="java" contentType="text/html; charset=UTF-8"
         pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>

<c:set var="pageTitle" value="나의 정보 - VROOM" scope="request"/>
<c:set var="pageCss" value="myInfo" scope="request"/>
<c:set var="pageCssDir" value="user" scope="request"/>

<jsp:include page="../common/header.jsp"/>

<meta name="context-path" content="${pageContext.request.contextPath}">

<div class="container">
    <div class="dashboard-container">
        <!-- Sidebar -->
        <aside class="sidebar">
            <ul class="sidebar-menu">
                <li class="sidebar-item"><a href="<c:url value='/member/myInfo'/>" class="sidebar-link active">나의 정보</a></li>
                <li class="sidebar-item"><a href="<c:url value='/member/vroomPay'/>" class="sidebar-link">부름 페이<br>(계좌 관리)</a></li>
                <li class="sidebar-item"><a href="<c:url value='/member/myActivity'/>" class="sidebar-link">나의 활동</a></li>
                <li class="sidebar-item"><a href="#" class="sidebar-link">설정</a></li>
                <li class="sidebar-item"><a href="#" class="sidebar-link">고객지원</a></li>
            </ul>
        </aside>

        <!-- Main Content -->
        <main class="main-content">
            <!-- Profile Header -->
            <div class="profile-header">
                <div class="profile-image" id="profileImage">
                    <c:choose>
                        <c:when test="${not empty profile.profileImage}">
                            <img src="${pageContext.request.contextPath}${profile.profileImage}" alt="Profile">
                        </c:when>
                        <c:otherwise>V</c:otherwise>
                    </c:choose>
                </div>
                <div class="profile-info">
                    <div class="profile-nickname" id="profileNickname">${profile.nickname}</div>
                    <div class="profile-temperature">
                        <span class="temp-label">매너온도</span>
                        <div class="temp-bar-container">
                            <div class="temp-bar-fill"></div>
                        </div>
                        <span class="temp-value-text">36.5℃</span>
                    </div>
                </div>
                <div class="profile-actions">
                    <a href="<c:url value='/member/myActivity'/>" class="action-btn">나의 활동</a>
                    <a href="<c:url value='/member/vroomPay'/>" class="action-btn">부름 페이</a>
                </div>
            </div>

            <!-- Tabs -->
            <div class="tabs-container">
                <button class="tab-btn active">전체</button>
                <button class="tab-btn">부름</button>
                <button class="tab-btn">예약</button>
                <button class="tab-btn">완료</button>
            </div>

            <!-- Grid -->
            <div class="activity-grid" id="activityGrid">
                <!-- Javascript will populate this -->
            </div>

            <!-- Pagination -->
            <div class="pagination-container" id="paginationContainer">
                <!-- Pagination will be generated by JavaScript -->
            </div>

            <!-- Withdrawal -->
            <div class="withdrawal-btn-container">
                <button class="withdrawal-btn" id="withdrawalBtn">탈퇴하기</button>
            </div>
        </main>
    </div>
</div>

<!-- Report Modal -->
<div class="modal-overlay" id="reportModal">
    <div class="modal-container">
        <div class="modal-header">
            <h2 class="modal-title">라이더 신고하기</h2>
            <button class="modal-close" id="reportModalClose">&times;</button>
        </div>

        <div class="modal-content report-modal-content">
            <div class="report-info">
                <div class="report-info-text">
                    신고 내용은 관리자가 검토 후 처리됩니다.<br>
                    허위 신고 시 서비스 이용이 제한될 수 있습니다.
                </div>
            </div>

            <div class="report-form-group">
                <label class="report-label" for="reportReason">신고 사유</label>
                <textarea class="report-textarea" id="reportReason"
                          placeholder="신고 사유를 자세히 작성해주세요.&#10;&#10;예시:&#10;- 약속 시간을 지키지 않았습니다&#10;- 물품을 분실했습니다&#10;- 불친절한 태도로 응대했습니다"></textarea>
                <div class="char-count">
                    <span id="reportCharCount">0</span> / 500
                </div>
            </div>
        </div>

        <div class="modal-actions">
            <button class="modal-btn modal-btn-cancel" id="reportCancel">취소</button>
            <button class="modal-btn modal-btn-save report-submit-btn" id="reportSubmit">신고하기</button>
        </div>
    </div>
</div>

<!-- Withdrawal Confirmation Modal -->
<div class="modal-overlay" id="withdrawalModal">
    <div class="modal-container">
        <div class="modal-header">
            <h2 class="modal-title">회원 탈퇴</h2>
            <button class="modal-close" id="withdrawalModalClose">&times;</button>
        </div>

        <div class="modal-content withdrawal-modal-content">
            <div class="withdrawal-notice">
                <div class="withdrawal-notice-title">⚠️ 탈퇴 전 유의사항</div>
                <div class="withdrawal-notice-text">
                    • 탈퇴 시 모든 활동 내역이 삭제됩니다<br>
                    • 부름 페이 잔액은 자동으로 환불됩니다<br>
                    • 진행 중인 부름/예약은 취소됩니다<br>
                    • 탈퇴 후 7일간 재가입이 제한됩니다
                </div>
            </div>

            <p class="withdrawal-warning">
                정말로 <strong>VROOM</strong>을 탈퇴하시겠습니까?<br>
                탈퇴를 진행하려면 비밀번호를 입력해주세요.
            </p>

            <div class="password-group">
                <input type="password" class="password-input" id="withdrawalPassword" placeholder="비밀번호를 입력하세요">
            </div>
        </div>

        <div class="modal-actions">
            <button class="modal-btn modal-btn-cancel" id="withdrawalCancel">취소</button>
            <button class="modal-btn modal-btn-save withdrawal-confirm-btn" id="withdrawalConfirm">탈퇴하기</button>
        </div>
    </div>
</div>

<!-- Profile Edit Modal -->
<div class="modal-overlay" id="profileModal">
    <div class="modal-container">
        <div class="modal-header">
            <h2 class="modal-title">프로필 수정</h2>
            <button class="modal-close" id="modalClose">&times;</button>
        </div>

        <div class="modal-tabs">
            <button class="modal-tab active" data-tab="image">프로필 이미지</button>
            <button class="modal-tab" data-tab="nickname">닉네임 변경</button>
        </div>

        <div class="modal-content">
            <!-- Profile Image Tab -->
            <div class="modal-tab-panel active" id="imagePanel">
                <div class="profile-preview">
                    <div class="preview-image" id="previewImage">
                        <c:choose>
                            <c:when test="${not empty profile.profileImage}">
                                <img src="${pageContext.request.contextPath}${profile.profileImage}" alt="Profile">
                            </c:when>
                            <c:otherwise>V</c:otherwise>
                        </c:choose>
                    </div>
                    <div class="upload-options">
                        <label for="imageUpload" class="upload-btn">이미지 업로드</label>
                        <input type="file" id="imageUpload" accept="image/*">
                        <button class="remove-btn" id="removeImage">기본 이미지로</button>
                    </div>
                </div>
                <p class="form-hint">JPG, PNG 파일만 가능합니다. 최대 5MB</p>
            </div>

            <!-- Nickname Tab -->
            <div class="modal-tab-panel" id="nicknamePanel">
                <div class="form-group">
                    <label class="form-label" for="nicknameInput">닉네임</label>
                    <input type="text" class="form-input" id="nicknameInput" placeholder="닉네임을 입력하세요" maxlength="20"
                           value="${profile.nickname}">
                    <div class="char-count">
                        <span id="charCount">9</span> / 20
                    </div>
                    <p class="form-hint">한글, 영문, 숫자만 사용 가능합니다. (2-20자)</p>
                </div>
            </div>
        </div>

        <div class="modal-actions">
            <button class="modal-btn modal-btn-cancel" id="modalCancel">취소</button>
            <button class="modal-btn modal-btn-save" id="modalSave">저장</button>
        </div>
    </div>
</div>

<!-- 숨겨진 데이터 영역 -->
<div id="errandDataContainer" class="hidden">
    <c:forEach var="errand" items="${errands}" varStatus="status">
        <div class="errand-data"
             data-id="${errand.errandsId}"
             data-title="${fn:escapeXml(errand.title)}"
             data-description="${fn:escapeXml(errand.description)}"
             data-price="<fmt:formatNumber value="${errand.rewardAmount}" pattern="#,###"/>"
             data-status="${errand.status}"
             data-location="${errand.gunguName} ${errand.dongName}"
             data-created="${errand.createdAt}">
        </div>
    </c:forEach>
</div>

<jsp:include page="../common/footer.jsp"/>

<script src="<c:url value='/static/user/js/myInfo.js'/>"></script>
</body>
</html>